<meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1">
<link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
<center>
    <img src="https://i.imgur.com/Qr9zuD2.png" class="banner">
    <div class="display">
        <h1>Download Ready...</h1>
        <img src="https://i.imgur.com/GajExEu.png" class="icon">
        <b><p style="color:red">You have requested the file:</p></b>
        <b>File Name:</b> Premuim.File.v2.zip<br/>
        <b>Size:</b> 0.49 MB<br/>
        <b>Uploaded:</b> 06-05-2019<br/>
        <b>Last download:</b> {%today_date%}<br/><br/> {%offers%}
        <br/><br/>
        <font style="font-size:0.8em;">Report illegal files, please
            <font style="color:red;cursor:pointer" id="report">click here</font> and send full link to us!</font>
    </div>
</center>
<script>
    $('#report').click(function(){alert('File Reported!, We will review your request.');})
</script>
